version: '3.8'

services:
  pingpal-frontend:
    container_name: pingpal-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # maps host:container ports
    environment:
      - JETTY_HTTP_PORT=8080